#!/bin/bash
#

echo -e "\nRunning Lint...\n"

files=$(git diff --cached --name-only --diff-filter=ACM | grep "\.js$")

if [ "$files" = "" ]; then
  exit 0
fi

if ! node_modules/eslint/bin/eslint.js ${files}
then
  echo -e "\033[31mESLint validation failed. Your commit contains files that should pass ESLint but do not. Please fix the errors and try again.\033[0m"
  exit 1
else
  echo -e "\033[32mESLint validation passed.\033[0m"
fi
